# Numpy Arrays

## numpy arrays

In [1]:
my_list = [1, 2, 3] #simple python list

print(my_list)

[1, 2, 3]


In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print(my_mat)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### np.arange

In [6]:
np.arange(0, 10) #np.arange({start}, {stope}, {step size})

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### zero arr